import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Ubuntu } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // customize as needed
  variable: "--font-ubuntu",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
